# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen2(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(340, 340)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.circularProgressBarBase = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBarBase.setGeometry(QtCore.QRect(10, 10, 320, 320))
        self.circularProgressBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBarBase.setObjectName("circularProgressBarBase")
        self.circularProgress = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularProgress.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularProgress.setStyleSheet("QFrame{\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(255, 85, 255, 0), stop:0.750 rgba(0, 170, 255, 255));\n"
"}\n"
"\n"
"\n"
"/*\n"
"\n"
"QFrame{\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(255, 85, 255, 0), stop:0.750 rgba(255, 0, 128, 255), stop:0.75 rgba(0, 170, 255, 255));\n"
"}\n"
"\n"
"\n"
"\n"
"*/\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"rgba(255, 85, 255, 0)\n"
"rgba(255, 0, 128, 255)\n"
"rgba(85, 255, 127, 255)\n"
"*/\n"
"\n"
"/*color: rgb(0, 170, 255);*/")
        self.circularProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgress.setObjectName("circularProgress")
        self.circularBg = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularBg.setStyleSheet("QFrame{\n"
"border-radius: 150px;\n"
"background-color: rgba(35, 57, 91,120); /*Morado Claro*/\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg.setObjectName("circularBg")
        self.container = QtWidgets.QFrame(self.circularProgressBarBase)
        self.container.setGeometry(QtCore.QRect(25, 25, 270, 270))
        self.container.setStyleSheet("QFrame{\n"
"border-radius: 135px;\n"
"background-color: rgb(35, 109, 152); /*35, 57, 91 Morado Fuerte*/\n"
"\n"
"}")
        self.container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.labelTitle = QtWidgets.QLabel(self.container)
        self.labelTitle.setGeometry(QtCore.QRect(10, 60, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.labelPorcentaje = QtWidgets.QLabel(self.container)
        self.labelPorcentaje.setGeometry(QtCore.QRect(10, 100, 251, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(58)
        font.setBold(True)
        font.setWeight(75)
        self.labelPorcentaje.setFont(font)
        self.labelPorcentaje.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.labelPorcentaje.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPorcentaje.setObjectName("labelPorcentaje")
        self.labelTitle_2 = QtWidgets.QLabel(self.container)
        self.labelTitle_2.setGeometry(QtCore.QRect(50, 200, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.labelTitle_2.setFont(font)
        self.labelTitle_2.setStyleSheet("QLabel{\n"
"border-radius: 10px;\n"
"color: #FFFFFF;\n"
"background-color: none;\n"
"}")
        self.labelTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle_2.setObjectName("labelTitle_2")
        self.circularBg.raise_()
        self.circularProgress.raise_()
        self.container.raise_()
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.labelTitle.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:600; color:#5e9af4;\">RED</span><span style=\" font-weight:600;\">GENHID</span></p></body></html>"))
        self.labelPorcentaje.setText(_translate("SplashScreen", "<html><head/><body><p>0<span style=\" vertical-align:super;\">%</span></p></body></html>"))
        self.labelTitle_2.setText(_translate("SplashScreen", "Calculando ..."))
